#!/bin/bash

# Some parts of this script should run with sudo, others not
if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

if [ -n "$SUDO_USER" ]; then 
	true_user=$SUDO_USER
	nonroot_cmd="sudo -u $true_user "
else
	true_user=$(whoami)
	nonroot_cmd=""
fi

cd "$(dirname "$0")"

echo "Update git submodules"
$nonroot_cmd git submodule update --init --recursive
echo "Done Updating git submodules"


echo "Install MEN MDIS for Linux System Package"
(cd 13MD05-90 && INSTALL -f)
echo "Done Installing MEN MDIS for Linux System Package"

echo "Install A25 drivers"
(cd A25_files && $nonroot_cmd make &&  make install && /opt/menlinux/DRIVERS/VME_16Z002/nodes.sh && echo “/usr/local/lib” > etc/ld.so.conf.d/menlinux.conf && ldconfig)
echo "Done Installing A25 drivers"

echo "Install complete!"


